name: camera_streams_app
description: "Demonstrates camera streams received from inference models 'cam_infer_models'"
publish_to: 'none'
version: 1.0.0+1

#resolution: workspace

environment:
  sdk: '^3.2.0'
  flutter: ">=3.16.0"

dependencies:
  camera: ^0.11.0+1
  camera_platform_interface: ^2.1.2
  camera_linux:
    git:
      url: https://github.com/toyota-connected/tcna-packages.git
      path: packages/camera/camera_linux
  ffi: ^2.1.3
  fixnum: ^1.1.0
  flutter:
    sdk: flutter

  logging: ^1.3.0
  native_toolchain_c: any

#gRPC
  async: ^2.13.0
  grpc: ^4.1.0
  protobuf: ^4.1.0

dev_dependencies:
  build_runner: ^2.1.10
  ffigen: ^19.0.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0



flutter:
  uses-material-design: true

  assets:
  - assets/traffic_signs/