name: camera_streams_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

#resolution: workspace

environment:
  sdk: '^3.2.0'
  flutter: ">=3.16.0"

dependencies:
  camera: ^0.11.0+1
  camera_linux:
    path: ../../camera/tcna-packages/packages/camera/camera_linux
  ffi: ^2.1.3
  flutter:
    sdk: flutter

  logging: ^1.3.0
  native_toolchain_c: any

#gRPC
  async: ^2.13.0
  grpc: ^4.1.0
  protobuf: ^4.1.0

dev_dependencies:
  build_runner: ^2.1.10
  ffigen: ^19.0.0


flutter:
  uses-material-design: true

  assets:
  - assets/traffic_signs/